# ./data/Sioux_Falls/
# ./data/Chicago_Sketch/
#./data/Tucson/
data_path: ./data/Tucson/
demand_randomness: False #False
avail_initial_path_flow: True # UE-based path flows (i.e., DTALite Path Flows)

multi_objective_function_setting: # dispersion weighting factors
  passenger_car_count: 1.0
  truck_count: 0.01
  passenger_car_vmt: 0.1
  truck_vmt: 0.01
  od_split: 0.1
  zonal: 0.1 # (0 means no consideration)

optimization_setting:
  training_steps: 10
  learning_rates: 0.01
  penalty_coefficient: 2.0

data_imputation:
  car_prop: 1.0
  truck_prop: 1.0

sensor_data_avail: False # False means there is no sensor data
sensor_data_setting:
  obs_time_duration: # 1440 minute-based
    obs_starting_time: 420
    obs_ending_time: 480